In [1]:
from ParseData import parseInfile, getData
from FeatureEngineering import FeatureEngineer, GenerateSmoothnessMetric
from TrainingMLAlgorithm import Train
from PredictSUAS import PredictSUAS

# Parsing the input data file of choice and extracting the values into the pandas data frame

input_file = "../datasets/testdata.txt"

df = parseInfile(input_file)
df.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,3709,"""TPM""","""DON 3709""",8,"""""",2,,42.557718900109691,-71.39987870415,3947.0,...,,,0,null,,null,,,,2022-07-13 15:15:48.347384

In [10]:
df = FeatureEngineer(df)
df.head()

c:\Users\nbohm\OneDrive - Villanova University\NSINStuff\NSIN\UIImplementation\FeatureEngineering.py:71: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  data["Speed"] = float(data["Speed"]) * 2.237

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT,Signal Persistence,Altitude Consistent,Drone
0,3709,"""TPM""","""DON 3709""",8,"""""",2,,42.557718900109691,-71.39987870415,3947.0,...,null,,null,,,,2022-07-13 15:15:48.347384,False,False,1

In [4]:
# Grabbing all of the data that will be used to train the ML algorithm
data = getData("../datasets/DODData/Default/")
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955

In [ ]:
# Adding in the Signal Persistence, Drone (YES OR NO), and other features 
data = FeatureEngineer(data)
data.head()

<class 'pandas.core.series.Series'>

TypeError: cannot convert the series to <class 'float'>

In [ ]:
# Adding in the Smoothness Metric
data = GenerateSmoothnessMetric(data)
data.head()

In [ ]:
new_model, new_scaler, new_imputer, new_X_train = Train(data)

PredictSUAS(df,new_model,new_scaler,new_imputer,new_X_train)