In [1]:
from ParseData import parseInfile, getData
from FeatureEngineering import FeatureEngineer, GenerateSmoothnessMetric

input_file = "../datasets/testdata.txt"

df = parseInfile(input_file)
df.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,2001,"""""","""DON 2001""",0,,5,,42.60274890953098,-71.602,200.0,...,,,,,,,,,,1970-01-01 00:00:00

In [2]:
data = getData("../datasets/DODData/Default/")
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955

In [3]:
data = FeatureEngineer(data)
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT,Signal Persistence,Altitude Consistent,Drone
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332,True,True,0
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863,True,True,0
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450,True,True,0
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965,True,True,0
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955,True,True,1

In [5]:
data = GenerateSmoothnessMetric(data)
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT,Signal Persistence,Altitude Consistent,Drone
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332,True,True,0
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863,True,True,0
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450,True,True,0
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965,True,True,0
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955,True,True,1