In [ ]:
from ParseData import parseInfile, getData
from FeatureEngineering import FeatureEngineer, GenerateSmoothnessMetric
from TrainingMLAlgorithm import Train
from PredictSUAS import PredictSUAS

# Parsing the input data file of choice and extracting the values into the pandas data frame

input_file = "../datasets/testdata.txt"

df = parseInfile(input_file)
df.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,2001,"""""","""DON 2001""",0,,5,,42.60274890953098,-71.602,200.0,...,,,,,,,,,,1970-01-01 00:00:00

In [2]:
# Grabbing all of the data that will be used to train the ML algorithm
data = getData("../datasets/DODData/Default/")
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Lob.OriginPosition.Lla.Altitude,Tracks.Lob.OriginPosition.Ecef,Tracks.Lob.OriginPosition.DataCase,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955

In [3]:
# Adding in the Signal Persistence, Drone (YES OR NO), and other features 
data = FeatureEngineer(data)
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT,Signal Persistence,Altitude Consistent,Drone
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332,True,True,0
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863,True,True,0
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450,True,True,0
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965,True,True,0
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955,True,True,1

In [4]:
# Adding in the Smoothness Metric
data = GenerateSmoothnessMetric(data)
data.head()

,ThreatId,SourceSystem,ThreatName,Priority,Description,Affiliation,Location,Location.Latitude,Location.Longitude,Location.Altitude,...,Tracks.Feature.Importance.Importance,Countermeasures.DeviceId,Countermeasures.Countermeasure,Countermeasures.State,Tracks.Feature.Countermeasures.DroneModel,Countermeasures.DroneModel,DetectionTimeInDT,Signal Persistence,Altitude Consistent,Drone
0,3784,TPM,DON 3784,8,NaN,2,NaN,42.491578,-71.311929,1263.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.495332,True,True,0
1,3786,TPM,DON 3786,8,NaN,2,NaN,42.414375,-71.351943,10382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:07:59.591863,True,True,0
2,3726,TPM,DON 3726,8,NaN,2,NaN,42.770994,-71.986791,5065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.233450,True,True,0
3,3794,TPM,DON 3794,8,NaN,2,NaN,42.287262,-71.336343,3855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:01.878965,True,True,0
4,3797,TPM,DON 3797,8,NaN,2,NaN,42.321132,-71.247895,4228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-13 15:08:02.521955,True,True,1

In [ ]:
new_model, new_scaler, new_imputer, new_X_train = Train(data)

PredictSUAS(df,new_model,new_scaler,new_imputer,new_X_train)

C:\Users\nbohm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [ 9 10 18 19 29 40 41 48 52 58 59] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\nbohm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

dt_clf: Accuracy = 0.9882858258492776
dt_clf: R2 score = 0.9142305983428856
xgb_clas: Accuracy = 0.9597813354158532
xgb_clas: R2 score = 0.6583068648735473
rnd_forest: Accuracy = 0.9902381882077314
rnd_forest: R2 score = 0.9269686247402125
  ThreatId SourceSystem  ThreatName Priority Description Affiliation Location  \
0     2001           ""  "DON 2001"        0                       5

   Location.Latitude Location.Longitude Location.Altitude  ...  \
0  42.60274890953098            -71.602             200.0  ...

  Tracks.Lob.OriginPosition.Lla.Altitude Tracks.Lob.OriginPosition.Ecef  \
0

  Tracks.Lob.OriginPosition.DataCase Tracks.Feature.Importance.Importance  \
0

  Countermeasures.DeviceId Countermeasures.Countermeasure  \
0

  Countermeasures.State Tracks.Feature.Countermeasures.DroneModel  \
0

  Countermeasures.DroneModel    DetectionTimeInDT
0                             1970-01-01 00:00:00

[1 rows x 116 columns]

KeyError: "['Drone'] not found in axis"